"""partition news_articles by published_at (monthly RANGE)

Revision ID: 3b7d2e9f1a4c
Revises: 2f8c4d1a3e7b
Create Date: 2026-03-03

Changes:
  - Recreate news_articles as PARTITION BY RANGE (published_at)
  - Primary key changed from (id) to (id, published_at)
  - Global UNIQUE on slug and guid replaced with composite unique
    indexes on (slug, published_at) and (guid, published_at) —
    PostgreSQL does not support global unique constraints on partitioned
    tables, but same-article re-ingestion always produces the same
    (slug, published_at) pair so dedup is still fully enforced.
  - Monthly child partitions created for 2025-01 through 2027-12
  - DEFAULT partition catches anything outside that range
"""
from typing import Sequence, Union

from alembic import op

revision: str = "3b7d2e9f1a4c"
down_revision: Union[str, Sequence[str], None] = "2f8c4d1a3e7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_ranges(start_year: int, start_month: int, end_year: int, end_month: int):
    """Yield (suffix, range_start, range_end) tuples for monthly partitions."""
    y, m = start_year, start_month
    while (y, m) <= (end_year, end_month):
        next_m = m % 12 + 1
        next_y = y + 1 if m == 12 else y
        yield (
            f"{y:04d}_{m:02d}",
            f"{y:04d}-{m:02d}-01",
            f"{next_y:04d}-{next_m:02d}-01",
        )
        y, m = next_y, next_m


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Preserve existing rows (dev env may have test data)
    # ------------------------------------------------------------------
    op.execute("ALTER TABLE news_articles RENAME TO news_articles_old")

    # Drop old indexes (they kept their names after the rename)
    op.execute("DROP INDEX IF EXISTS ix_news_articles_published_at")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_slug")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_source_id")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_source_name")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_author")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_category")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_cvss_score")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_tags_gin")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_keywords_gin")
    op.execute("DROP INDEX IF EXISTS ix_news_articles_cve_ids_gin")
    op.execute("DROP INDEX IF EXISTS uix_news_articles_slug_date")
    op.execute("DROP INDEX IF EXISTS uix_news_articles_guid_date")
    op.execute("ALTER TABLE news_articles_old DROP CONSTRAINT IF EXISTS uq_news_articles_guid")

    # ------------------------------------------------------------------
    # 2. Create the partitioned parent table
    #    Primary key must include the partition key (published_at).
    #    id uses GENERATED BY DEFAULT AS IDENTITY so the sequence still
    #    auto-increments but can be overridden during data migration.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE news_articles (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
            slug         VARCHAR(255)   NOT NULL,
            guid         VARCHAR(2048),
            source_id    INTEGER,
            source_name  VARCHAR(255),
            title        VARCHAR(500)   NOT NULL,
            author       VARCHAR(255),
            "desc"       TEXT,
            content_html TEXT,
            image_url    VARCHAR(2048),
            tags         TEXT[]         NOT NULL DEFAULT '{}',
            keywords     TEXT[]         NOT NULL DEFAULT '{}',
            published_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            severity     VARCHAR(50),
            type         VARCHAR(50)    NOT NULL,
            category     VARCHAR(100)   NOT NULL,
            source_url   VARCHAR(2048),
            cvss_score   NUMERIC(4, 1),
            cve_ids      TEXT[],
            raw_metadata JSONB,
            created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            updated_at   TIMESTAMPTZ,
            PRIMARY KEY (id, published_at)
        ) PARTITION BY RANGE (published_at)
    """)

    # ------------------------------------------------------------------
    # 3. Foreign key (partitioned → non-partitioned is supported)
    # ------------------------------------------------------------------
    op.execute("""
        ALTER TABLE news_articles
        ADD CONSTRAINT fk_news_articles_source_id
        FOREIGN KEY (source_id) REFERENCES feed_sources(id) ON DELETE SET NULL
    """)

    # ------------------------------------------------------------------
    # 4. Indexes on the parent propagate automatically to every partition.
    #
    #    Unique indexes must include the partition key (published_at).
    #    Dedup still works: slug = sha256(guid)[:8] + title-slug, and
    #    published_at comes from the RSS item's actual publish date, so
    #    re-ingesting the same article always hits the same (slug, published_at).
    # ------------------------------------------------------------------
    op.execute(
        "CREATE UNIQUE INDEX uix_news_articles_slug_date "
        "ON news_articles (slug, published_at)"
    )
    op.execute(
        "CREATE UNIQUE INDEX uix_news_articles_guid_date "
        "ON news_articles (guid, published_at) WHERE guid IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_published_at "
        "ON news_articles (published_at DESC)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_source_id "
        "ON news_articles (source_id)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_source_name "
        "ON news_articles (source_name)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_author "
        "ON news_articles (author)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_category "
        "ON news_articles (category)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_cvss_score "
        "ON news_articles (cvss_score) WHERE cvss_score IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_tags_gin "
        "ON news_articles USING gin (tags)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_keywords_gin "
        "ON news_articles USING gin (keywords)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_cve_ids_gin "
        "ON news_articles USING gin (cve_ids)"
    )

    # ------------------------------------------------------------------
    # 5. Monthly child partitions: 2025-01 through 2027-12
    # ------------------------------------------------------------------
    for suffix, range_start, range_end in _month_ranges(2025, 1, 2027, 12):
        op.execute(f"""
            CREATE TABLE news_articles_{suffix}
            PARTITION OF news_articles
            FOR VALUES FROM ('{range_start}') TO ('{range_end}')
        """)

    # DEFAULT partition catches anything outside 2025-01 – 2027-12
    op.execute(
        "CREATE TABLE news_articles_default "
        "PARTITION OF news_articles DEFAULT"
    )

    # ------------------------------------------------------------------
    # 6. Migrate existing data
    # ------------------------------------------------------------------
    op.execute("""
        INSERT INTO news_articles (
            id, slug, guid, source_id, source_name, title, author,
            "desc", content_html, image_url, tags, keywords, published_at,
            severity, type, category, source_url, cvss_score, cve_ids,
            raw_metadata, created_at, updated_at
        )
        SELECT
            id, slug, guid, source_id, source_name, title, author,
            "desc", content_html, image_url, tags, keywords, published_at,
            severity, type, category, source_url, cvss_score, cve_ids,
            raw_metadata, created_at, updated_at
        FROM news_articles_old
    """)

    # Advance the identity sequence past the max migrated id
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('news_articles', 'id'),
            COALESCE((SELECT MAX(id) FROM news_articles), 0) + 1,
            false
        )
    """)

    # ------------------------------------------------------------------
    # 7. Drop the old table
    # ------------------------------------------------------------------
    op.execute("DROP TABLE news_articles_old")


def downgrade() -> None:
    # Drop the partitioned table and all child partitions
    op.execute("DROP TABLE IF EXISTS news_articles CASCADE")

    # Recreate the non-partitioned table as left by 2f8c4d1a3e7b
    op.execute("""
        CREATE TABLE news_articles (
            id           SERIAL         NOT NULL,
            slug         VARCHAR(255)   NOT NULL,
            guid         VARCHAR(2048),
            source_id    INTEGER,
            source_name  VARCHAR(255),
            title        VARCHAR(500)   NOT NULL,
            author       VARCHAR(255),
            "desc"       TEXT,
            content_html TEXT,
            image_url    VARCHAR(2048),
            tags         TEXT[]         NOT NULL DEFAULT '{}',
            keywords     TEXT[]         NOT NULL DEFAULT '{}',
            published_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            severity     VARCHAR(50),
            type         VARCHAR(50)    NOT NULL,
            category     VARCHAR(100)   NOT NULL,
            source_url   VARCHAR(2048),
            cvss_score   NUMERIC(4, 1),
            cve_ids      TEXT[],
            raw_metadata JSONB,
            created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            updated_at   TIMESTAMPTZ,
            PRIMARY KEY (id)
        )
    """)
    op.execute(
        "CREATE UNIQUE CONSTRAINT uq_news_articles_guid ON news_articles (guid)"
    )
    op.execute(
        "CREATE UNIQUE INDEX ix_news_articles_slug ON news_articles (slug)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_published_at ON news_articles (published_at)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_source_id ON news_articles (source_id)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_source_name ON news_articles (source_name)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_author ON news_articles (author)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_cvss_score ON news_articles (cvss_score)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_tags_gin ON news_articles USING gin (tags)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_keywords_gin "
        "ON news_articles USING gin (keywords)"
    )
    op.execute(
        "CREATE INDEX ix_news_articles_cve_ids_gin "
        "ON news_articles USING gin (cve_ids)"
    )
    op.execute("""
        ALTER TABLE news_articles
        ADD CONSTRAINT fk_news_articles_source_id
        FOREIGN KEY (source_id) REFERENCES feed_sources(id) ON DELETE SET NULL
    """)
